/**
 * CandidateActionsCard — shows the 2-3 candidate collection actions
 * generated by the strategy engine, with the AI-selected winner highlighted.
 */

import { CheckCircle2, Circle, Zap, Clock, DollarSign, TrendingUp } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const CHANNEL_COLOR = {
  "Call":              "text-blue-600 dark:text-blue-400",
  "Anchor Escalation": "text-red-600 dark:text-red-400",
  "Field Visit":       "text-purple-600 dark:text-purple-400",
  "Legal":             "text-orange-600 dark:text-orange-400",
  "Email":             "text-teal-600 dark:text-teal-400",
  "None":              "text-muted-foreground",
};

const COST_COLOR = {
  "Zero":      "text-green-600 dark:text-green-400",
  "Minimal":   "text-green-600 dark:text-green-400",
  "Low":       "text-teal-600 dark:text-teal-400",
  "Medium":    "text-amber-600 dark:text-amber-400",
  "High":      "text-red-500",
  "Very High": "text-red-600 dark:text-red-400",
};

function RecoveryBar({ value }) {
  const pct = Math.round(value * 100);
  const color = pct >= 70 ? "bg-green-500" : pct >= 50 ? "bg-amber-500" : "bg-red-400";
  return (
    <div className="flex items-center gap-2">
      <div className="flex-1 h-1.5 rounded-full bg-muted overflow-hidden">
        <div className={`h-full rounded-full ${color}`} style={{ width: `${pct}%` }} />
      </div>
      <span className="text-xs font-semibold text-foreground w-8 text-right">{pct}%</span>
    </div>
  );
}

export function CandidateActionsCard({ candidates = [], selectionRationale = "", urgency = "Medium" }) {
  if (!candidates || candidates.length === 0) return null;

  return (
    <Card className="border-blue-400/25">
      <CardHeader className="pb-2 bg-gradient-to-r from-blue-500/8 via-blue-500/4 to-background border-b border-blue-400/20">
        <CardTitle className="flex items-center gap-2 text-sm">
          <Zap className="h-4 w-4 text-blue-500" />
          Candidate Actions
          <span className="text-xs font-normal text-muted-foreground ml-1">
            — AI evaluated {candidates.length} options
          </span>
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-3 space-y-2">
        {candidates.map((c, i) => (
          <div
            key={i}
            className={`rounded-lg border p-3 transition-all ${
              c.is_selected
                ? "border-primary/40 bg-gradient-to-br from-primary/10 to-primary/5 shadow-sm"
                : "border-border bg-muted/20 opacity-70"
            }`}
          >
            {/* Header row */}
            <div className="flex items-start gap-2.5 mb-2">
              <div className="mt-0.5 shrink-0">
                {c.is_selected
                  ? <CheckCircle2 className="h-4 w-4 text-primary" />
                  : <Circle className="h-4 w-4 text-muted-foreground/40" />
                }
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <p className={`text-sm font-semibold ${c.is_selected ? "text-foreground" : "text-muted-foreground"}`}>
                    {c.action_label}
                  </p>
                  {c.is_selected && (
                    <span className="text-xs px-1.5 py-0.5 rounded-full bg-primary/15 text-primary border border-primary/25 font-semibold">
                      AI Selected
                    </span>
                  )}
                </div>
                <p className="text-xs text-muted-foreground mt-0.5 leading-relaxed">{c.rationale}</p>
              </div>
            </div>

            {/* Metrics */}
            <div className="ml-6.5 space-y-1.5">
              <RecoveryBar value={c.recovery_estimate} />
              <div className="flex items-center gap-4 text-xs">
                <span className={`flex items-center gap-1 ${CHANNEL_COLOR[c.channel] || "text-muted-foreground"}`}>
                  <TrendingUp className="h-3 w-3" /> {c.channel}
                </span>
                <span className="flex items-center gap-1 text-muted-foreground">
                  <Clock className="h-3 w-3" /> {c.timeline_hours}h SLA
                </span>
                <span className={`flex items-center gap-1 ${COST_COLOR[c.cost] || "text-muted-foreground"}`}>
                  <DollarSign className="h-3 w-3" /> {c.cost}
                </span>
                {c.selection_score > 0 && (
                  <span className="ml-auto text-muted-foreground">
                    score: <strong className="text-foreground">{(c.selection_score * 100).toFixed(0)}</strong>
                  </span>
                )}
              </div>
            </div>
          </div>
        ))}

        {/* Selection rationale */}
        {selectionRationale && (
          <div className="mt-1 p-2.5 rounded-lg bg-muted/40 border border-border">
            <p className="text-xs font-semibold text-muted-foreground mb-1">Selection Rationale</p>
            <p className="text-xs text-foreground leading-relaxed">{selectionRationale}</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
