"""
Mock invoice portfolio used as a development/demo dataset.

In production, replace with live database queries. The same invoice IDs
are referenced across prediction, prioritization, and forecast services.
"""

from datetime import date, timedelta

today = date.today()


MOCK_INVOICES = [
    {
        "invoice_id": "INV-2024-001",
        "invoice_number": "INV-2024-001",
        "customer_name": "Apex Manufacturing Inc.",
        "customer_id": 1,
        "industry": "Manufacturing",
        "amount": 85_000.0,
        "currency": "USD",
        "issue_date": today - timedelta(days=75),
        "due_date": today - timedelta(days=45),
        "status": "overdue",
        "days_overdue": 45,
        "risk_label": "High",
        "credit_score": 580,
        "avg_days_to_pay": 52.0,
        "num_late_payments": 5,
        "payment_terms": 30,
        "customer_total_overdue": 145_000.0,
        "pay_7_days": 0.08,
        "pay_15_days": 0.18,
        "pay_30_days": 0.32,
        "recommended_action": "Send Formal Demand Letter",
    },
    {
        "invoice_id": "INV-2024-002",
        "invoice_number": "INV-2024-002",
        "customer_name": "BlueSky Logistics Ltd.",
        "customer_id": 2,
        "industry": "Logistics",
        "amount": 42_500.0,
        "currency": "USD",
        "issue_date": today - timedelta(days=50),
        "due_date": today - timedelta(days=20),
        "status": "overdue",
        "days_overdue": 20,
        "risk_label": "Medium",
        "credit_score": 680,
        "avg_days_to_pay": 38.0,
        "num_late_payments": 2,
        "payment_terms": 30,
        "customer_total_overdue": 42_500.0,
        "pay_7_days": 0.22,
        "pay_15_days": 0.45,
        "pay_30_days": 0.71,
        "recommended_action": "Make Collection Call",
    },
    {
        "invoice_id": "INV-2024-003",
        "invoice_number": "INV-2024-003",
        "customer_name": "GreenField Retail Corp.",
        "customer_id": 3,
        "industry": "Retail",
        "amount": 18_750.0,
        "currency": "USD",
        "issue_date": today - timedelta(days=35),
        "due_date": today - timedelta(days=5),
        "status": "overdue",
        "days_overdue": 5,
        "risk_label": "Low",
        "credit_score": 760,
        "avg_days_to_pay": 29.0,
        "num_late_payments": 0,
        "payment_terms": 30,
        "customer_total_overdue": 18_750.0,
        "pay_7_days": 0.55,
        "pay_15_days": 0.80,
        "pay_30_days": 0.94,
        "recommended_action": "Send Payment Reminder Email",
    },
    {
        "invoice_id": "INV-2024-004",
        "invoice_number": "INV-2024-004",
        "customer_name": "TechNova Solutions",
        "customer_id": 4,
        "industry": "Technology",
        "amount": 125_000.0,
        "currency": "USD",
        "issue_date": today - timedelta(days=110),
        "due_date": today - timedelta(days=80),
        "status": "overdue",
        "days_overdue": 80,
        "risk_label": "High",
        "credit_score": 540,
        "avg_days_to_pay": 72.0,
        "num_late_payments": 8,
        "payment_terms": 30,
        "customer_total_overdue": 210_000.0,
        "pay_7_days": 0.03,
        "pay_15_days": 0.07,
        "pay_30_days": 0.18,
        "recommended_action": "Escalate to Collections Agency",
    },
    {
        "invoice_id": "INV-2024-005",
        "invoice_number": "INV-2024-005",
        "customer_name": "Solaris Energy Partners",
        "customer_id": 5,
        "industry": "Energy",
        "amount": 67_200.0,
        "currency": "USD",
        "issue_date": today - timedelta(days=45),
        "due_date": today + timedelta(days=15),
        "status": "open",
        "days_overdue": 0,
        "risk_label": "Medium",
        "credit_score": 710,
        "avg_days_to_pay": 33.0,
        "num_late_payments": 1,
        "payment_terms": 60,
        "customer_total_overdue": 0.0,
        "pay_7_days": 0.15,
        "pay_15_days": 0.62,
        "pay_30_days": 0.88,
        "recommended_action": "Send Payment Reminder Email",
    },
    {
        "invoice_id": "INV-2024-006",
        "invoice_number": "INV-2024-006",
        "customer_name": "NorthStar Healthcare",
        "customer_id": 6,
        "industry": "Healthcare",
        "amount": 31_400.0,
        "currency": "USD",
        "issue_date": today - timedelta(days=60),
        "due_date": today - timedelta(days=30),
        "status": "overdue",
        "days_overdue": 30,
        "risk_label": "Medium",
        "credit_score": 645,
        "avg_days_to_pay": 44.0,
        "num_late_payments": 3,
        "payment_terms": 30,
        "customer_total_overdue": 31_400.0,
        "pay_7_days": 0.18,
        "pay_15_days": 0.38,
        "pay_30_days": 0.61,
        "recommended_action": "Schedule Payment Plan Discussion",
    },
    {
        "invoice_id": "INV-2024-007",
        "invoice_number": "INV-2024-007",
        "customer_name": "Pacific Steel Works",
        "customer_id": 7,
        "industry": "Manufacturing",
        "amount": 52_800.0,
        "currency": "USD",
        "issue_date": today - timedelta(days=90),
        "due_date": today - timedelta(days=60),
        "status": "overdue",
        "days_overdue": 60,
        "risk_label": "High",
        "credit_score": 600,
        "avg_days_to_pay": 58.0,
        "num_late_payments": 6,
        "payment_terms": 30,
        "customer_total_overdue": 52_800.0,
        "pay_7_days": 0.05,
        "pay_15_days": 0.12,
        "pay_30_days": 0.26,
        "recommended_action": "Make Collection Call",
    },
    {
        "invoice_id": "INV-2024-008",
        "invoice_number": "INV-2024-008",
        "customer_name": "Clearwater Financial",
        "customer_id": 8,
        "industry": "Finance",
        "amount": 9_800.0,
        "currency": "USD",
        "issue_date": today - timedelta(days=20),
        "due_date": today + timedelta(days=10),
        "status": "open",
        "days_overdue": 0,
        "risk_label": "Low",
        "credit_score": 800,
        "avg_days_to_pay": 22.0,
        "num_late_payments": 0,
        "payment_terms": 30,
        "customer_total_overdue": 0.0,
        "pay_7_days": 0.30,
        "pay_15_days": 0.85,
        "pay_30_days": 0.97,
        "recommended_action": "No Action Required",
    },
]


def get_invoice_by_id(invoice_id: str) -> dict | None:
    return next((inv for inv in MOCK_INVOICES if inv["invoice_id"] == invoice_id), None)


def get_portfolio_summary() -> dict:
    total_outstanding = sum(
        inv["amount"] for inv in MOCK_INVOICES if inv["status"] in ("open", "overdue")
    )
    overdue_count = sum(1 for inv in MOCK_INVOICES if inv["status"] == "overdue")
    risk_breakdown = {"High": 0, "Medium": 0, "Low": 0}
    for inv in MOCK_INVOICES:
        risk_breakdown[inv.get("risk_label", "Medium")] += 1

    return {
        "total_invoices": len(MOCK_INVOICES),
        "total_outstanding": total_outstanding,
        "overdue_count": overdue_count,
        "risk_breakdown": risk_breakdown,
    }
