"""Pydantic schemas for the Collection Strategy Optimization engine."""

from typing import Optional
from pydantic import BaseModel, Field


class StrategyRequest(BaseModel):
    """All signals needed to compute an optimised collection strategy."""

    invoice_id: str
    customer_name: str
    invoice_amount: float = Field(..., gt=0)
    days_overdue: int = Field(..., ge=0)

    # From delay prediction
    delay_probability: float = Field(..., ge=0, le=1)
    risk_tier: str  # "High" | "Medium" | "Low"

    # Business signals
    urgency_override: Optional[str] = None  # "Critical" | "High" | "Medium" | "Low"
    recoverability_score: float = Field(default=0.7, ge=0, le=1)
    nach_applicable: bool = False
    borrower_type: str = "corporate"  # "corporate" | "sme" | "individual"
    automation_feasible: bool = True

    # From behavior engine
    behavior_type: Optional[str] = None
    followup_dependency: Optional[bool] = None


class CandidateAction(BaseModel):
    """One option generated by the Candidate Action Generator."""

    action_label: str
    channel: str       # "Call" | "Email" | "Legal" | "Field Visit" | "Anchor Escalation"
    rationale: str
    timeline_hours: int
    cost: str          # "Minimal" | "Low" | "Medium" | "High" | "Very High"
    recovery_estimate: float = Field(..., ge=0, le=1)
    selection_score: float = Field(default=0.0, ge=0, le=1)   # computed by agentic selector
    is_selected: bool = False                                   # True = agent's final choice


class StrategyResponse(BaseModel):
    """Optimised collection strategy with priority ranking + candidate actions."""

    invoice_id: str
    priority_score: int = Field(..., ge=0, le=100)
    priority_rank: Optional[int] = None
    recommended_action: str
    urgency: str       # "Critical" | "High" | "Medium" | "Low"
    channel: str
    reason: str
    automation_flag: bool
    next_action_in_hours: int

    # Candidate Action Generator — 2-3 options before final selection
    candidate_actions: list[CandidateAction] = []
    # Agentic Final Selector rationale
    selection_rationale: Optional[str] = None

    # Enriched invoice fields — populated by the portfolio endpoint
    customer_name: Optional[str] = None
    amount: Optional[float] = None
    days_overdue: Optional[int] = None
    risk_label: Optional[str] = None
    risk_tier: Optional[str] = None
    delay_probability: Optional[float] = None
    behavior_type: Optional[str] = None
    nach_recommended: Optional[bool] = None
