/**
 * Client-side mock data for development without a running backend.
 * Mirrors the shape of actual API responses exactly.
 */

export const mockSummary = {
  total_invoices: 8,
  total_outstanding: 484650,
  overdue_count: 6,
  overdue_amount: 345450,
  amount_at_risk: 263450,
  high_risk_count: 3,
  risk_breakdown: { High: 3, Medium: 3, Low: 2 },
};

export const mockDSO = {
  predicted_dso: 52.3,
  current_dso: 48.5,
  dso_trend: "worsening",
  benchmark_dso: 45.0,
};

export const mockCashflow = {
  next_7_days_inflow: 48200,
  next_30_days_inflow: 187400,
  expected_7_day_collections: 48200,
  expected_30_day_collections: 187400,
  amount_at_risk: 263450,
  shortfall_signal: true,
  borrower_concentration_risk: "High",
  overdue_carry_forward: 157650,
  confidence: 0.82,
  daily_breakdown: Array.from({ length: 30 }, (_, i) => {
    const d = new Date();
    d.setDate(d.getDate() + i);
    const base = 4000 + Math.random() * 8000;
    return {
      date: d.toISOString().split("T")[0],
      predicted_inflow: Math.round(base),
      lower_bound: Math.round(base * 0.75),
      upper_bound: Math.round(base * 1.25),
    };
  }),
};

export const mockWorklist = [
  {
    invoice_id: "INV-2024-004",
    customer_name: "TechNova Solutions",
    amount: 125000,
    days_overdue: 80,
    risk_label: "High",
    risk_tier: "High",
    delay_probability: 0.82,
    priority_score: 97,
    priority_rank: 1,
    recommended_action: "Escalate to Anchor",
    urgency: "Critical",
    behavior_type: "High Risk Defaulter",
    nach_recommended: true,
  },
  {
    invoice_id: "INV-2024-001",
    customer_name: "Apex Manufacturing Inc.",
    amount: 85000,
    days_overdue: 45,
    risk_label: "High",
    risk_tier: "High",
    delay_probability: 0.68,
    priority_score: 88,
    priority_rank: 2,
    recommended_action: "Formal Demand Letter",
    urgency: "Critical",
    behavior_type: "Chronic Delayed Payer",
    nach_recommended: true,
  },
  {
    invoice_id: "INV-2024-007",
    customer_name: "Pacific Steel Works",
    amount: 52800,
    days_overdue: 60,
    risk_label: "High",
    risk_tier: "High",
    delay_probability: 0.74,
    priority_score: 83,
    priority_rank: 3,
    recommended_action: "Collection Call + Email",
    urgency: "Critical",
    behavior_type: "Chronic Delayed Payer",
    nach_recommended: true,
  },
  {
    invoice_id: "INV-2024-006",
    customer_name: "NorthStar Healthcare",
    amount: 31400,
    days_overdue: 30,
    risk_label: "Medium",
    risk_tier: "Medium",
    delay_probability: 0.39,
    priority_score: 55,
    priority_rank: 4,
    recommended_action: "Follow-up Email + Call",
    urgency: "High",
    behavior_type: "Reminder Driven Payer",
    nach_recommended: true,
  },
  {
    invoice_id: "INV-2024-002",
    customer_name: "BlueSky Logistics Ltd.",
    amount: 42500,
    days_overdue: 20,
    risk_label: "Medium",
    risk_tier: "Medium",
    delay_probability: 0.29,
    priority_score: 42,
    priority_rank: 5,
    recommended_action: "Collection Call",
    urgency: "Medium",
    behavior_type: "Occasional Late Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-005",
    customer_name: "Solaris Energy Partners",
    amount: 67200,
    days_overdue: 0,
    risk_label: "Medium",
    risk_tier: "Medium",
    delay_probability: 0.12,
    priority_score: 28,
    priority_rank: 6,
    recommended_action: "Automated Payment Reminder",
    urgency: "Medium",
    behavior_type: "Occasional Late Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-003",
    customer_name: "GreenField Retail Corp.",
    amount: 18750,
    days_overdue: 5,
    risk_label: "Low",
    risk_tier: "Low",
    delay_probability: 0.06,
    priority_score: 10,
    priority_rank: 7,
    recommended_action: "Automated Reminder",
    urgency: "Low",
    behavior_type: "Consistent Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-008",
    customer_name: "Clearwater Financial",
    amount: 9800,
    days_overdue: 0,
    risk_label: "Low",
    risk_tier: "Low",
    delay_probability: 0.03,
    priority_score: 5,
    priority_rank: 8,
    recommended_action: "No Action Required",
    urgency: "Low",
    behavior_type: "Consistent Payer",
    nach_recommended: false,
  },
];

export const mockInvoiceDetail = {
  "INV-2024-001": {
    invoice_id: "INV-2024-001",
    invoice_number: "INV-2024-001",
    customer_name: "Apex Manufacturing Inc.",
    customer_id: "1",
    industry: "Manufacturing",
    amount: 85000,
    currency: "USD",
    issue_date: "2024-02-01",
    due_date: "2024-03-01",
    status: "overdue",
    days_overdue: 45,
    risk_label: "High",
    credit_score: 580,
    avg_days_to_pay: 52,
    num_late_payments: 5,
    pay_7_days: 0.08,
    pay_15_days: 0.18,
    pay_30_days: 0.32,
    recommended_action: "Formal Demand Letter",
    shap_explanation: {
      top_features: [
        { feature_name: "days_overdue", feature_value: 45, shap_value: 0.32, impact: "negative" },
        { feature_name: "customer_credit_score", feature_value: 580, shap_value: -0.18, impact: "positive" },
        { feature_name: "num_late_payments", feature_value: 5, shap_value: 0.22, impact: "negative" },
        { feature_name: "invoice_amount", feature_value: 85000, shap_value: 0.08, impact: "negative" },
        { feature_name: "avg_days_to_pay", feature_value: 52, shap_value: 0.06, impact: "negative" },
      ],
      base_value: 0.45,
      prediction_value: 0.72,
    },
    payment_behavior: {
      customer_id: "1",
      customer_name: "Apex Manufacturing Inc.",
      behavior_type: "Chronic Delayed Payer",
      on_time_ratio: 31.0,
      avg_delay_days: 22.0,
      trend: "Worsening",
      payment_style: "Chronic Late + High DPD",
      behavior_risk_score: 82.0,
      followup_dependency: true,
      nach_recommended: true,
      behavior_summary:
        "Apex Manufacturing Inc. is classified as a 'Chronic Delayed Payer'. On-time payment ratio is 31% with an average delay of 22 days. Payment trend is worsening. NACH/auto-debit is recommended. Behavior risk score: 82/100.",
    },
    delay_prediction: {
      invoice_id: "INV-2024-001",
      delay_probability: 0.68,
      risk_score: 68,
      risk_tier: "High",
      top_drivers: [
        "45 days already overdue",
        "5 prior delays",
        "Chronic delayed payer behavior pattern",
        "Credit score 580 below threshold",
      ],
      detailed_drivers: [
        { driver: "45 days past due date", impact: "high", direction: "increases_risk" },
        { driver: "5 prior late payments", impact: "high", direction: "increases_risk" },
        { driver: "Customer classified as Chronic Delayed Payer", impact: "high", direction: "increases_risk" },
        { driver: "Low credit score (580)", impact: "high", direction: "increases_risk" },
      ],
      model_version: "rule-engine-v2",
    },
    strategy: {
      invoice_id: "INV-2024-001",
      priority_score: 88,
      priority_rank: 2,
      recommended_action: "Formal Demand Letter",
      urgency: "Critical",
      channel: "Legal",
      reason: "Priority Critical: delay probability 68% + high risk tier + 45 DPD + chronic delayed payer behavior.",
      automation_flag: false,
      next_action_in_hours: 12,
    },
    ai_recommendation: {
      recommended_action: "Formal Demand Letter",
      priority: "Critical",
      timeline: "Within 24 Hours",
      reasoning:
        "High-value invoice ($85K) is 45 days overdue with only 32% probability of payment in 30 days. Customer has 5 historical late payments and a low credit score of 580.",
      additional_notes: "Consider escalating to legal review if no response within 72 hours.",
    },
  },
  "INV-2024-004": {
    invoice_id: "INV-2024-004",
    invoice_number: "INV-2024-004",
    customer_name: "TechNova Solutions",
    customer_id: "4",
    industry: "Technology",
    amount: 125000,
    currency: "USD",
    issue_date: "2024-01-01",
    due_date: "2024-02-01",
    status: "overdue",
    days_overdue: 80,
    risk_label: "High",
    credit_score: 540,
    avg_days_to_pay: 72,
    num_late_payments: 8,
    pay_7_days: 0.03,
    pay_15_days: 0.07,
    pay_30_days: 0.18,
    recommended_action: "Escalate to Anchor",
    shap_explanation: {
      top_features: [
        { feature_name: "days_overdue", feature_value: 80, shap_value: 0.48, impact: "negative" },
        { feature_name: "num_late_payments", feature_value: 8, shap_value: 0.35, impact: "negative" },
        { feature_name: "customer_credit_score", feature_value: 540, shap_value: 0.28, impact: "negative" },
        { feature_name: "invoice_amount", feature_value: 125000, shap_value: 0.15, impact: "negative" },
        { feature_name: "avg_days_to_pay", feature_value: 72, shap_value: 0.12, impact: "negative" },
      ],
      base_value: 0.45,
      prediction_value: 0.92,
    },
    payment_behavior: {
      customer_id: "4",
      customer_name: "TechNova Solutions",
      behavior_type: "High Risk Defaulter",
      on_time_ratio: 18.0,
      avg_delay_days: 38.0,
      trend: "Worsening",
      payment_style: "Erratic + Non-Responsive",
      behavior_risk_score: 94.0,
      followup_dependency: true,
      nach_recommended: true,
      behavior_summary:
        "TechNova Solutions is classified as a 'High Risk Defaulter'. On-time payment ratio is 18% with an average delay of 38 days. Payment trend is worsening. NACH/auto-debit is recommended. Behavior risk score: 94/100.",
    },
    delay_prediction: {
      invoice_id: "INV-2024-004",
      delay_probability: 0.82,
      risk_score: 82,
      risk_tier: "High",
      top_drivers: [
        "80 days already overdue",
        "8 prior delays",
        "High risk defaulter behavior pattern",
        "Credit score 540 below threshold",
      ],
      detailed_drivers: [
        { driver: "80 days past due date", impact: "high", direction: "increases_risk" },
        { driver: "8 prior late payments", impact: "high", direction: "increases_risk" },
        { driver: "High Risk Defaulter pattern", impact: "high", direction: "increases_risk" },
        { driver: "Low credit score (540)", impact: "high", direction: "increases_risk" },
      ],
      model_version: "rule-engine-v2",
    },
    strategy: {
      invoice_id: "INV-2024-004",
      priority_score: 97,
      priority_rank: 1,
      recommended_action: "Escalate to Anchor",
      urgency: "Critical",
      channel: "Anchor Escalation",
      reason: "Priority Critical: delay probability 82% + high risk tier + 80 DPD + high risk defaulter behavior.",
      automation_flag: false,
      next_action_in_hours: 4,
    },
    ai_recommendation: {
      recommended_action: "Escalate to Anchor",
      priority: "Critical",
      timeline: "Immediate — Within 4 Hours",
      reasoning:
        "TechNova Solutions ($125K, 80 DPD) shows an 82% delay probability and a 'High Risk Defaulter' behavior profile. 8 prior late payments with a credit score of 540 indicate systemic payment failure.",
      additional_notes: "Initiate anchor escalation and consider legal review in parallel.",
    },
  },
};

export const mockWhatIfBaseline = {
  predicted_recovery_pct: 68.0,
  cashflow_shift: 0,
  dso_shift: 0,
  baseline_recovery_pct: 68.0,
  baseline_cashflow: 320000,
  baseline_dso: 48.5,
  scenario_summary: "Baseline scenario — no changes applied.",
};
