/**
 * Client-side mock data for development without a running backend.
 * Mirrors the shape of actual API responses exactly.
 * All monetary values are in INR (₹).
 */

export const mockSummary = {
  total_invoices: 15,
  total_outstanding: 32300000,
  overdue_count: 11,
  overdue_amount: 26450000,
  amount_at_risk: 19400000,
  high_risk_count: 6,
  risk_breakdown: { High: 6, Medium: 4, Low: 5 },
};

export const mockDSO = {
  predicted_dso: 52.3,
  current_dso: 48.5,
  dso_trend: "worsening",
  benchmark_dso: 45.0,
};

export const mockCashflow = {
  next_7_days_inflow: 980000,
  next_30_days_inflow: 4850000,
  expected_7_day_collections: 980000,
  expected_30_day_collections: 4850000,
  amount_at_risk: 19400000,
  shortfall_signal: true,
  borrower_concentration_risk: "High",
  overdue_carry_forward: 1750000,
  confidence: 0.82,
  daily_breakdown: Array.from({ length: 30 }, (_, i) => {
    const d = new Date();
    d.setDate(d.getDate() + i);
    const base = 40000 + Math.random() * 80000;
    return {
      date: d.toISOString().split("T")[0],
      predicted_inflow: Math.round(base),
      lower_bound: Math.round(base * 0.75),
      upper_bound: Math.round(base * 1.25),
    };
  }),
};

export const mockWorklist = [
  {
    invoice_id: "INV-2024-004",
    customer_name: "TechNova Solutions",
    amount: 4250000,
    days_overdue: 80,
    risk_label: "High",
    risk_tier: "High",
    delay_probability: 0.82,
    priority_score: 97,
    priority_rank: 1,
    recommended_action: "Escalate to Anchor",
    urgency: "Critical",
    behavior_type: "High Risk Defaulter",
    nach_recommended: true,
  },
  {
    invoice_id: "INV-2024-001",
    customer_name: "Apex Manufacturing Inc.",
    amount: 2850000,
    days_overdue: 45,
    risk_label: "High",
    risk_tier: "High",
    delay_probability: 0.68,
    priority_score: 88,
    priority_rank: 2,
    recommended_action: "Formal Demand Letter",
    urgency: "Critical",
    behavior_type: "Chronic Delayed Payer",
    nach_recommended: true,
  },
  {
    invoice_id: "INV-2024-007",
    customer_name: "Pacific Steel Works",
    amount: 1750000,
    days_overdue: 60,
    risk_label: "High",
    risk_tier: "High",
    delay_probability: 0.74,
    priority_score: 83,
    priority_rank: 3,
    recommended_action: "Collection Call + Email",
    urgency: "Critical",
    behavior_type: "Chronic Delayed Payer",
    nach_recommended: true,
  },
  {
    invoice_id: "INV-2024-006",
    customer_name: "NorthStar Healthcare",
    amount: 1050000,
    days_overdue: 30,
    risk_label: "Medium",
    risk_tier: "Medium",
    delay_probability: 0.39,
    priority_score: 55,
    priority_rank: 4,
    recommended_action: "Follow-up Email + Call",
    urgency: "High",
    behavior_type: "Reminder Driven Payer",
    nach_recommended: true,
  },
  {
    invoice_id: "INV-2024-002",
    customer_name: "BlueSky Logistics Ltd.",
    amount: 1425000,
    days_overdue: 20,
    risk_label: "Medium",
    risk_tier: "Medium",
    delay_probability: 0.29,
    priority_score: 42,
    priority_rank: 5,
    recommended_action: "Collection Call",
    urgency: "Medium",
    behavior_type: "Occasional Late Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-005",
    customer_name: "Solaris Energy Partners",
    amount: 2250000,
    days_overdue: 0,
    risk_label: "Medium",
    risk_tier: "Medium",
    delay_probability: 0.12,
    priority_score: 28,
    priority_rank: 6,
    recommended_action: "Automated Payment Reminder",
    urgency: "Medium",
    behavior_type: "Occasional Late Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-003",
    customer_name: "GreenField Retail Corp.",
    amount: 625000,
    days_overdue: 5,
    risk_label: "Low",
    risk_tier: "Low",
    delay_probability: 0.06,
    priority_score: 10,
    priority_rank: 7,
    recommended_action: "Automated Reminder",
    urgency: "Low",
    behavior_type: "Consistent Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-008",
    customer_name: "Clearwater Financial",
    amount: 325000,
    days_overdue: 0,
    risk_label: "Low",
    risk_tier: "Low",
    delay_probability: 0.03,
    priority_score: 5,
    priority_rank: 8,
    recommended_action: "No Action Required",
    urgency: "Low",
    behavior_type: "Consistent Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-009",
    customer_name: "Adani Infrastructure Ltd.",
    amount: 4500000,
    days_overdue: 90,
    risk_label: "High",
    risk_tier: "High",
    delay_probability: 0.86,
    priority_score: 99,
    priority_rank: 1,
    recommended_action: "Field Collection Visit",
    urgency: "Critical",
    behavior_type: "High Risk Defaulter",
    nach_recommended: true,
  },
  {
    invoice_id: "INV-2024-010",
    customer_name: "Mahindra Auto Parts",
    amount: 875000,
    days_overdue: 12,
    risk_label: "Medium",
    risk_tier: "Medium",
    delay_probability: 0.26,
    priority_score: 38,
    priority_rank: 9,
    recommended_action: "Collection Call",
    urgency: "Medium",
    behavior_type: "Occasional Late Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-011",
    customer_name: "Tata Chemicals Ltd.",
    amount: 3200000,
    days_overdue: 0,
    risk_label: "Low",
    risk_tier: "Low",
    delay_probability: 0.05,
    priority_score: 8,
    priority_rank: 14,
    recommended_action: "Automated Reminder",
    urgency: "Low",
    behavior_type: "Consistent Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-012",
    customer_name: "Infosys Consulting Pvt. Ltd.",
    amount: 525000,
    days_overdue: 22,
    risk_label: "Medium",
    risk_tier: "Medium",
    delay_probability: 0.32,
    priority_score: 45,
    priority_rank: 8,
    recommended_action: "Follow-up Email + Call",
    urgency: "High",
    behavior_type: "Reminder Driven Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-013",
    customer_name: "HDFC Leasing Co.",
    amount: 1250000,
    days_overdue: 55,
    risk_label: "High",
    risk_tier: "High",
    delay_probability: 0.71,
    priority_score: 86,
    priority_rank: 4,
    recommended_action: "Collection Call + Email",
    urgency: "Critical",
    behavior_type: "Chronic Delayed Payer",
    nach_recommended: true,
  },
  {
    invoice_id: "INV-2024-014",
    customer_name: "Sun Pharma Distributors",
    amount: 975000,
    days_overdue: 0,
    risk_label: "Low",
    risk_tier: "Low",
    delay_probability: 0.07,
    priority_score: 9,
    priority_rank: 13,
    recommended_action: "Automated Payment Reminder",
    urgency: "Low",
    behavior_type: "Consistent Payer",
    nach_recommended: false,
  },
  {
    invoice_id: "INV-2024-015",
    customer_name: "Reliance Textiles Ltd.",
    amount: 1850000,
    days_overdue: 35,
    risk_label: "High",
    risk_tier: "High",
    delay_probability: 0.60,
    priority_score: 78,
    priority_rank: 5,
    recommended_action: "Formal Demand Letter",
    urgency: "High",
    behavior_type: "Chronic Delayed Payer",
    nach_recommended: true,
  },
];

export const mockInvoiceDetail = {
  "INV-2024-001": {
    invoice_id: "INV-2024-001",
    invoice_number: "INV-2024-001",
    customer_name: "Apex Manufacturing Inc.",
    customer_id: "1",
    industry: "Manufacturing",
    amount: 2850000,
    currency: "INR",
    issue_date: "2024-02-01",
    due_date: "2024-03-01",
    status: "overdue",
    days_overdue: 45,
    risk_label: "High",
    credit_score: 580,
    avg_days_to_pay: 52,
    num_late_payments: 5,
    pay_7_days: 0.08,
    pay_15_days: 0.18,
    pay_30_days: 0.32,
    recommended_action: "Formal Demand Letter",
    shap_explanation: {
      top_features: [
        { feature_name: "days_overdue", feature_value: 45, shap_value: 0.32, impact: "negative" },
        { feature_name: "customer_credit_score", feature_value: 580, shap_value: -0.18, impact: "positive" },
        { feature_name: "num_late_payments", feature_value: 5, shap_value: 0.22, impact: "negative" },
        { feature_name: "invoice_amount", feature_value: 2850000, shap_value: 0.08, impact: "negative" },
        { feature_name: "avg_days_to_pay", feature_value: 52, shap_value: 0.06, impact: "negative" },
      ],
      base_value: 0.45,
      prediction_value: 0.72,
    },
    payment_behavior: {
      customer_id: "1",
      customer_name: "Apex Manufacturing Inc.",
      behavior_type: "Chronic Delayed Payer",
      on_time_ratio: 31.0,
      avg_delay_days: 22.0,
      trend: "Worsening",
      payment_style: "Chronic Late + High DPD",
      behavior_risk_score: 82.0,
      followup_dependency: true,
      nach_recommended: true,
      behavior_summary:
        "Apex Manufacturing Inc. is classified as a 'Chronic Delayed Payer'. On-time payment ratio is 31% with an average delay of 22 days. Payment trend is worsening. NACH/auto-debit is recommended. Behavior risk score: 82/100.",
    },
    delay_prediction: {
      invoice_id: "INV-2024-001",
      delay_probability: 0.68,
      risk_score: 68,
      risk_tier: "High",
      top_drivers: [
        "45 days already overdue",
        "5 prior delays",
        "Chronic delayed payer behavior pattern",
        "Credit score 580 below threshold",
      ],
      detailed_drivers: [
        { driver: "45 days past due date", impact: "high", direction: "increases_risk" },
        { driver: "5 prior late payments", impact: "high", direction: "increases_risk" },
        { driver: "Customer classified as Chronic Delayed Payer", impact: "high", direction: "increases_risk" },
        { driver: "Low credit score (580)", impact: "high", direction: "increases_risk" },
      ],
      model_version: "rule-engine-v2",
    },
    strategy: {
      invoice_id: "INV-2024-001",
      priority_score: 88,
      priority_rank: 2,
      recommended_action: "Formal Demand Letter",
      urgency: "Critical",
      channel: "Legal",
      reason: "Priority Critical: delay probability 68% + high risk tier + 45 DPD + chronic delayed payer behavior.",
      automation_flag: false,
      next_action_in_hours: 12,
    },
    ai_recommendation: {
      recommended_action: "Formal Demand Letter",
      priority: "Critical",
      timeline: "Within 24 Hours",
      reasoning:
        "High-value invoice (₹28.5L) is 45 days overdue with only 32% probability of payment in 30 days. Customer has 5 historical late payments and a low credit score of 580.",
      additional_notes: "Consider escalating to legal review if no response within 72 hours.",
    },
  },
  "INV-2024-004": {
    invoice_id: "INV-2024-004",
    invoice_number: "INV-2024-004",
    customer_name: "TechNova Solutions",
    customer_id: "4",
    industry: "Technology",
    amount: 4250000,
    currency: "INR",
    issue_date: "2024-01-01",
    due_date: "2024-02-01",
    status: "overdue",
    days_overdue: 80,
    risk_label: "High",
    credit_score: 540,
    avg_days_to_pay: 72,
    num_late_payments: 8,
    pay_7_days: 0.03,
    pay_15_days: 0.07,
    pay_30_days: 0.18,
    recommended_action: "Escalate to Anchor",
    shap_explanation: {
      top_features: [
        { feature_name: "days_overdue", feature_value: 80, shap_value: 0.48, impact: "negative" },
        { feature_name: "num_late_payments", feature_value: 8, shap_value: 0.35, impact: "negative" },
        { feature_name: "customer_credit_score", feature_value: 540, shap_value: 0.28, impact: "negative" },
        { feature_name: "invoice_amount", feature_value: 4250000, shap_value: 0.15, impact: "negative" },
        { feature_name: "avg_days_to_pay", feature_value: 72, shap_value: 0.12, impact: "negative" },
      ],
      base_value: 0.45,
      prediction_value: 0.92,
    },
    payment_behavior: {
      customer_id: "4",
      customer_name: "TechNova Solutions",
      behavior_type: "High Risk Defaulter",
      on_time_ratio: 18.0,
      avg_delay_days: 38.0,
      trend: "Worsening",
      payment_style: "Erratic + Non-Responsive",
      behavior_risk_score: 94.0,
      followup_dependency: true,
      nach_recommended: true,
      behavior_summary:
        "TechNova Solutions is classified as a 'High Risk Defaulter'. On-time payment ratio is 18% with an average delay of 38 days. Payment trend is worsening. NACH/auto-debit is recommended. Behavior risk score: 94/100.",
    },
    delay_prediction: {
      invoice_id: "INV-2024-004",
      delay_probability: 0.82,
      risk_score: 82,
      risk_tier: "High",
      top_drivers: [
        "80 days already overdue",
        "8 prior delays",
        "High risk defaulter behavior pattern",
        "Credit score 540 below threshold",
      ],
      detailed_drivers: [
        { driver: "80 days past due date", impact: "high", direction: "increases_risk" },
        { driver: "8 prior late payments", impact: "high", direction: "increases_risk" },
        { driver: "High Risk Defaulter pattern", impact: "high", direction: "increases_risk" },
        { driver: "Low credit score (540)", impact: "high", direction: "increases_risk" },
      ],
      model_version: "rule-engine-v2",
    },
    strategy: {
      invoice_id: "INV-2024-004",
      priority_score: 97,
      priority_rank: 1,
      recommended_action: "Escalate to Anchor",
      urgency: "Critical",
      channel: "Anchor Escalation",
      reason: "Priority Critical: delay probability 82% + high risk tier + 80 DPD + high risk defaulter behavior.",
      automation_flag: false,
      next_action_in_hours: 4,
    },
    ai_recommendation: {
      recommended_action: "Escalate to Anchor",
      priority: "Critical",
      timeline: "Immediate — Within 4 Hours",
      reasoning:
        "TechNova Solutions (₹42.5L, 80 DPD) shows an 82% delay probability and a 'High Risk Defaulter' behavior profile. 8 prior late payments with a credit score of 540 indicate systemic payment failure.",
      additional_notes: "Initiate anchor escalation and consider legal review in parallel.",
    },
  },
};

export const mockBorrowerPortfolio = [
  {
    customer_id: "4",
    customer_name: "TechNova Solutions",
    industry: "Technology",
    total_outstanding: 4250000,
    overdue_invoice_count: 1,
    borrower_risk_tier: "High",
    borrower_risk_score: 88,
    weighted_delay_probability: 0.82,
    expected_recovery_rate: 0.18,
    at_risk_amount: 4250000,
    escalation_recommended: true,
    relationship_action: "Escalate Relationship — Legal Review",
    concentration_pct: 29.3,
  },
  {
    customer_id: "1",
    customer_name: "Apex Manufacturing Inc.",
    industry: "Manufacturing",
    total_outstanding: 2850000,
    overdue_invoice_count: 1,
    borrower_risk_tier: "High",
    borrower_risk_score: 74,
    weighted_delay_probability: 0.68,
    expected_recovery_rate: 0.32,
    at_risk_amount: 2850000,
    escalation_recommended: true,
    relationship_action: "Place on Credit Hold + Escalate",
    concentration_pct: 19.6,
  },
  {
    customer_id: "7",
    customer_name: "Pacific Steel Works",
    industry: "Manufacturing",
    total_outstanding: 1750000,
    overdue_invoice_count: 1,
    borrower_risk_tier: "High",
    borrower_risk_score: 69,
    weighted_delay_probability: 0.74,
    expected_recovery_rate: 0.26,
    at_risk_amount: 1750000,
    escalation_recommended: true,
    relationship_action: "Activate NACH Mandate + Collection Call",
    concentration_pct: 12.0,
  },
  {
    customer_id: "5",
    customer_name: "Solaris Energy Partners",
    industry: "Energy",
    total_outstanding: 2250000,
    overdue_invoice_count: 0,
    borrower_risk_tier: "Medium",
    borrower_risk_score: 38,
    weighted_delay_probability: 0.12,
    expected_recovery_rate: 0.88,
    at_risk_amount: 0,
    escalation_recommended: false,
    relationship_action: "Follow-up Email + Call",
    concentration_pct: 15.5,
  },
  {
    customer_id: "6",
    customer_name: "NorthStar Healthcare",
    industry: "Healthcare",
    total_outstanding: 1050000,
    overdue_invoice_count: 1,
    borrower_risk_tier: "Medium",
    borrower_risk_score: 48,
    weighted_delay_probability: 0.39,
    expected_recovery_rate: 0.61,
    at_risk_amount: 0,
    escalation_recommended: false,
    relationship_action: "Collection Call + Payment Plan",
    concentration_pct: 7.2,
  },
  {
    customer_id: "2",
    customer_name: "BlueSky Logistics Ltd.",
    industry: "Logistics",
    total_outstanding: 1425000,
    overdue_invoice_count: 1,
    borrower_risk_tier: "Medium",
    borrower_risk_score: 34,
    weighted_delay_probability: 0.29,
    expected_recovery_rate: 0.71,
    at_risk_amount: 0,
    escalation_recommended: false,
    relationship_action: "Follow-up Email + Call",
    concentration_pct: 9.8,
  },
  {
    customer_id: "3",
    customer_name: "GreenField Retail Corp.",
    industry: "Retail",
    total_outstanding: 625000,
    overdue_invoice_count: 1,
    borrower_risk_tier: "Low",
    borrower_risk_score: 12,
    weighted_delay_probability: 0.06,
    expected_recovery_rate: 0.94,
    at_risk_amount: 0,
    escalation_recommended: false,
    relationship_action: "Standard Reminder Cycle",
    concentration_pct: 4.3,
  },
  {
    customer_id: "8",
    customer_name: "Clearwater Financial",
    industry: "Finance",
    total_outstanding: 325000,
    overdue_invoice_count: 0,
    borrower_risk_tier: "Low",
    borrower_risk_score: 5,
    weighted_delay_probability: 0.03,
    expected_recovery_rate: 0.97,
    at_risk_amount: 0,
    escalation_recommended: false,
    relationship_action: "Standard Reminder Cycle",
    concentration_pct: 2.2,
  },
];

export const mockWatchlist = {
  total_flagged: 6,
  critical_count: 2,
  high_count: 4,
  customers: [
    {
      customer_id: "4", customer_name: "TechNova Solutions", industry: "Technology",
      is_flagged: true, risk_level: "Critical", overall_sentinel_score: 92,
      recommendation: "Immediate escalation. Multiple systemic signals detected. Do not extend credit.",
      last_checked: new Date().toISOString().split("T")[0],
      high_signal_count: 2, medium_signal_count: 1,
      signals: [
        { signal_type: "leadership_change", severity: "High", description: "CTO resigned last month; payment authorization disrupted.", source: "LinkedIn", detected_at: "2024-03-28" },
        { signal_type: "news_alert", severity: "High", description: "Company cited in NCLT proceedings; debt restructuring under review.", source: "Economic Times", detected_at: "2024-04-02" },
        { signal_type: "email_anomaly", severity: "Medium", description: "Accounts payable mailbox bouncing since 7 days.", source: "Email Monitor", detected_at: "2024-04-08" },
      ],
    },
    {
      customer_id: "9", customer_name: "Adani Infrastructure Ltd.", industry: "Infrastructure",
      is_flagged: true, risk_level: "Critical", overall_sentinel_score: 88,
      recommendation: "Halt credit extension. AP contact unreachable. Initiate field recovery immediately.",
      last_checked: new Date().toISOString().split("T")[0],
      high_signal_count: 2, medium_signal_count: 0,
      signals: [
        { signal_type: "ap_contact_failure", severity: "High", description: "AP contact unreachable for 14 consecutive days.", source: "CRM", detected_at: "2024-04-01" },
        { signal_type: "news_alert", severity: "High", description: "SEBI regulatory inquiry reported; infrastructure expansion stalled.", source: "Mint", detected_at: "2024-04-05" },
      ],
    },
    {
      customer_id: "13", customer_name: "HDFC Leasing Co.", industry: "Finance",
      is_flagged: true, risk_level: "High", overall_sentinel_score: 74,
      recommendation: "Monitor closely. New CFO onboarded — expect payment delays during transition.",
      last_checked: new Date().toISOString().split("T")[0],
      high_signal_count: 0, medium_signal_count: 2,
      signals: [
        { signal_type: "leadership_change", severity: "Medium", description: "New CFO onboarded 2 weeks ago; payment approval cycle extended.", source: "LinkedIn", detected_at: "2024-04-06" },
        { signal_type: "email_anomaly", severity: "Medium", description: "Email response time 3x above baseline.", source: "Email Monitor", detected_at: "2024-04-09" },
      ],
    },
    {
      customer_id: "15", customer_name: "Reliance Textiles Ltd.", industry: "Manufacturing",
      is_flagged: true, risk_level: "High", overall_sentinel_score: 68,
      recommendation: "GST dispute affecting cash flow. Offer payment plan to secure partial recovery.",
      last_checked: new Date().toISOString().split("T")[0],
      high_signal_count: 0, medium_signal_count: 1,
      signals: [
        { signal_type: "news_alert", severity: "Medium", description: "Tax dispute under GST audit; cash locked in escrow impacting payables.", source: "Tax Monitor", detected_at: "2024-04-11" },
      ],
    },
    {
      customer_id: "7", customer_name: "Pacific Steel Works", industry: "Manufacturing",
      is_flagged: true, risk_level: "High", overall_sentinel_score: 65,
      recommendation: "Steel sector under pressure. Escalate to anchor if no payment in 7 days.",
      last_checked: new Date().toISOString().split("T")[0],
      high_signal_count: 0, medium_signal_count: 1,
      signals: [
        { signal_type: "sector_news", severity: "Medium", description: "Steel sector under margin pressure; export orders down 23%.", source: "Business Line", detected_at: "2024-04-07" },
      ],
    },
    {
      customer_id: "1", customer_name: "Apex Manufacturing Inc.", industry: "Manufacturing",
      is_flagged: true, risk_level: "High", overall_sentinel_score: 62,
      recommendation: "Sector-level stress. Prioritize collection call before month-end.",
      last_checked: new Date().toISOString().split("T")[0],
      high_signal_count: 0, medium_signal_count: 1,
      signals: [
        { signal_type: "sector_news", severity: "Medium", description: "Auto sector cash crunch reported; component manufacturers facing 45–60 day delays.", source: "Business Standard", detected_at: "2024-04-10" },
      ],
    },
  ],
};

export const mockWhatIfBaseline = {
  predicted_recovery_pct: 68.0,
  cashflow_shift: 0,
  dso_shift: 0,
  baseline_recovery_pct: 68.0,
  baseline_cashflow: 32000000,
  baseline_dso: 48.5,
  scenario_summary: "Baseline scenario — no changes applied.",
};
